/** UniFi model codes → human-readable names. The controller reports terse
 *  codes (`USWED72`); the UI shows the product name. Unknown codes fall back
 *  to the raw code, so a new model is never blank. Add codes as they show up
 *  on the fleet. */
const MODEL_NAMES: Record<string, string> = {
  // Gateways
  UDMPROMAX: 'UDM Pro Max',
  // Reported by the UDM Pro Max on Network 9/10 firmware.
  UDMEA4C: 'UDM Pro Max',
  UDMPRO: 'UDM Pro',
  UDMSE: 'UDM SE',
  UDMR: 'Dream Router',
  UDR: 'Dream Router',
  UDR7: 'Dream Router 7',
  UDM: 'UDM',
  UCGMAX: 'Cloud Gateway Max',
  UCGULTRA: 'Cloud Gateway Ultra',
  UCGFIBER: 'Cloud Gateway Fiber',
  UXG: 'UXG Pro',
  UXGLITE: 'UXG Lite',
  EFG: 'Enterprise Fortress Gateway',
  UCI: 'Cable Modem',
  // Switches
  USL8A: 'USW Aggregation',
  USXG24: 'USW Pro Aggregation',
  USWED72: 'USW Pro XG 24 PoE',
  USWED35: 'USW Flex 2.5G 5',
  USWED37: 'USW Flex 2.5G 8 PoE',
  USPM16P: 'USW Pro Max 16 PoE',
  USPM16: 'USW Pro Max 16',
  USPM24P: 'USW Pro Max 24 PoE',
  USPM24: 'USW Pro Max 24',
  USPM48P: 'USW Pro Max 48 PoE',
  USPM48: 'USW Pro Max 48',
  USFXG: 'USW Flex XG',
  USF5P: 'USW Flex',
  USMINI: 'USW Flex Mini',
  USL8LP: 'USW Lite 8 PoE',
  USL8P: 'USW Lite 8 PoE',
  USL16P: 'USW Lite 16 PoE',
  USL16LP: 'USW Lite 16 PoE',
  USL24P: 'USW Lite 24 PoE',
  USL24: 'USW 24',
  USL48P: 'USW 48 PoE',
  US8P60: 'US 8 60W',
  US8P150: 'US 8 150W',
  US16P150: 'US 16 150W',
  US24P250: 'US 24 250W',
  US24PRO: 'USW Pro 24',
  US24PRO2: 'USW Pro 24 PoE',
  US48PRO: 'USW Pro 48',
  USE24P: 'USW Enterprise 24 PoE',
  USE8P: 'USW Enterprise 8 PoE',
  // Access points
  U7PRO: 'U7 Pro',
  U7PROMAX: 'U7 Pro Max',
  U7LITE: 'U7 Lite',
  U7LR: 'U7 Long Range',
  U7IW: 'U7 In-Wall',
  U7OUT: 'U7 Outdoor',
  U7PXG: 'U7 Pro XG',
  U7PXGW: 'U7 Pro XGS',
  UKPW: 'UK Ultra',
  U6PRO: 'U6 Pro',
  U6LR: 'U6 Long Range',
  U6LITE: 'U6 Lite',
  U6M: 'U6 Mesh',
  U6IW: 'U6 In-Wall',
  U6ENT: 'U6 Enterprise',
  U6EXT: 'U6 Extender',
  UAP6: 'U6 Lite',
  UAP6MP: 'U6 Pro',
  UAPL6: 'U6 Long Range',
  UAPLU6: 'U6 Lite',
  U6PLUS: 'U6+',
  UALR6v3: 'U6 Long Range',
  UAL6: 'U6 Lite',
  UAIW6: 'U6 In-Wall',
  UAE6: 'U6 Enterprise',
  UAP: 'UAP',
  UAPAC: 'UAP AC',
  UAPACLITE: 'UAP AC Lite',
  UAPACLR: 'UAP AC LR',
  UAPACPRO: 'UAP AC Pro',
  UAPACM: 'UAP AC Mesh',
  UAPACMPRO: 'UAP AC Mesh Pro',
  UAPACIW: 'UAP AC In-Wall',
  UAPACHD: 'UAP AC HD',
  UAPNANOHD: 'UAP nanoHD',
  UAPFLEXHD: 'UAP FlexHD',
  UAPBEACONHD: 'UAP BeaconHD',
};

export function modelName(code: string | undefined | null): string {
  if (!code) return 'Unknown';
  return MODEL_NAMES[code] ?? MODEL_NAMES[code.toUpperCase()] ?? code;
}
